### ISSUE TITLE
Test issue when using node-jre on Linux

### ISSUE THREAD

**Issue by edasque** [schreiben/node-jre#11]
On Linux Alpine (node8-alpine) on Docker, this is what I get when installing node-jre:

```
> node-jre@0.2.3 install /src/node_modules/node-jre
> node install.js

Downloading from:  https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz

/src/node_modules/node-jre/index.js:105
    .stdout.trim() === 'No smoke!';
           ^

TypeError: Cannot read property 'trim' of null
    at exports.smoketest (/src/node_modules/node-jre/index.js:105:12)
    at Request.request.get.on.on.on (/src/node_modules/node-jre/index.js:141:30)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/src/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Any idea why that would be happening?

I'll try another Docker image with debian to see if I have the same issue.

**Comment by edasque** [comment]
Seems to have worked in Debian. The issue remains with Alpine, probably not a huge deal.
